/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.infox.telas;
import br.com.infox.dal.ModuloConexao;
import java.text.DateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import java.sql.*;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author lucas
 */
public class TelaPrincipal extends javax.swing.JFrame {

    Connection conexao = null;
    PreparedStatement statement = null;
    ResultSet result = null;
    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
        conexao = ModuloConexao.conector();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktop = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        lbl_Usuario = new javax.swing.JLabel();
        lbl_Data = new javax.swing.JLabel();
        Menu = new javax.swing.JMenuBar();
        menu_Cadastro = new javax.swing.JMenu();
        menu_CadastroCliente = new javax.swing.JMenuItem();
        menu_CadastroOS = new javax.swing.JMenuItem();
        menu_CadastroUsuario = new javax.swing.JMenuItem();
        menu_Relatorio = new javax.swing.JMenu();
        menuRelatorioCliente = new javax.swing.JMenuItem();
        menuRelatorioServico = new javax.swing.JMenuItem();
        menu_Ajuda = new javax.swing.JMenu();
        menu_AjudaSobre = new javax.swing.JMenuItem();
        menu_Opcoes = new javax.swing.JMenu();
        menu_OpcoesSair = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("x - Sistema de controle de OS");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        javax.swing.GroupLayout desktopLayout = new javax.swing.GroupLayout(desktop);
        desktop.setLayout(desktopLayout);
        desktopLayout.setHorizontalGroup(
            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 577, Short.MAX_VALUE)
        );
        desktopLayout.setVerticalGroup(
            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 461, Short.MAX_VALUE)
        );

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/infox/icones/x.png"))); // NOI18N
        jLabel1.setText("x");

        lbl_Usuario.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lbl_Usuario.setText("Usuário");

        lbl_Data.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lbl_Data.setText("Data");

        menu_Cadastro.setText("Cadastro");

        menu_CadastroCliente.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_DOWN_MASK));
        menu_CadastroCliente.setText("Cliente");
        menu_CadastroCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_CadastroClienteActionPerformed(evt);
            }
        });
        menu_Cadastro.add(menu_CadastroCliente);

        menu_CadastroOS.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.ALT_DOWN_MASK));
        menu_CadastroOS.setText("OS");
        menu_CadastroOS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_CadastroOSActionPerformed(evt);
            }
        });
        menu_Cadastro.add(menu_CadastroOS);

        menu_CadastroUsuario.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.ALT_DOWN_MASK));
        menu_CadastroUsuario.setText("Usuários");
        menu_CadastroUsuario.setEnabled(false);
        menu_CadastroUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_CadastroUsuarioActionPerformed(evt);
            }
        });
        menu_Cadastro.add(menu_CadastroUsuario);

        Menu.add(menu_Cadastro);

        menu_Relatorio.setText("Relatório");
        menu_Relatorio.setEnabled(false);

        menuRelatorioCliente.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.ALT_DOWN_MASK));
        menuRelatorioCliente.setText("Clientes");
        menuRelatorioCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuRelatorioClienteActionPerformed(evt);
            }
        });
        menu_Relatorio.add(menuRelatorioCliente);

        menuRelatorioServico.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.ALT_DOWN_MASK));
        menuRelatorioServico.setText("Serviços");
        menuRelatorioServico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuRelatorioServicoActionPerformed(evt);
            }
        });
        menu_Relatorio.add(menuRelatorioServico);

        Menu.add(menu_Relatorio);

        menu_Ajuda.setText("Ajuda");

        menu_AjudaSobre.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_1, java.awt.event.InputEvent.ALT_DOWN_MASK));
        menu_AjudaSobre.setText("Sobre");
        menu_AjudaSobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_AjudaSobreActionPerformed(evt);
            }
        });
        menu_Ajuda.add(menu_AjudaSobre);

        Menu.add(menu_Ajuda);

        menu_Opcoes.setText("Opções");

        menu_OpcoesSair.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_4, java.awt.event.InputEvent.ALT_DOWN_MASK));
        menu_OpcoesSair.setText("Sair");
        menu_OpcoesSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_OpcoesSairActionPerformed(evt);
            }
        });
        menu_Opcoes.add(menu_OpcoesSair);

        Menu.add(menu_Opcoes);

        setJMenuBar(Menu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(desktop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_Data)
                            .addComponent(lbl_Usuario))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(desktop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(lbl_Usuario)
                .addGap(37, 37, 37)
                .addComponent(lbl_Data)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(76, 76, 76))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void menu_CadastroClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_CadastroClienteActionPerformed
        // Chamando a tela TelaCliente
        TelaCliente cliente = new TelaCliente();
        cliente.setVisible(true);
        desktop.add(cliente);
    }//GEN-LAST:event_menu_CadastroClienteActionPerformed

    private void menu_CadastroOSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_CadastroOSActionPerformed
        //chamando a tela os
        TelaOS os = new TelaOS();
        os.setVisible(true);
        desktop.add(os);
    }//GEN-LAST:event_menu_CadastroOSActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        /*As linhas abaixo substituem a label lbl_Data pela data atual do sistema
        ao iniciar o form(telaprincipal)*/
        Date data = new Date();
        DateFormat formatador = DateFormat.getDateInstance(DateFormat.SHORT);
        lbl_Data.setText(formatador.format(data));
    }//GEN-LAST:event_formWindowActivated

    private void menu_OpcoesSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_OpcoesSairActionPerformed
        // Exibi a caixa de dialogo
        int sair = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja sair?", "Atenção", JOptionPane.YES_NO_OPTION);
        if(sair == JOptionPane.YES_OPTION){
            System.exit(0);
        }
    }//GEN-LAST:event_menu_OpcoesSairActionPerformed

    private void menu_AjudaSobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_AjudaSobreActionPerformed
        // Será chamado a tela TelaSobre
        TelaSobre sobre = new TelaSobre ();
        sobre.setVisible(true);
    }//GEN-LAST:event_menu_AjudaSobreActionPerformed

    private void menu_CadastroUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_CadastroUsuarioActionPerformed
        // Chamando a TelaUsuario
        TelaUsuario usuario = new TelaUsuario();
        usuario.setVisible(true);
        desktop.add(usuario);
       
    }//GEN-LAST:event_menu_CadastroUsuarioActionPerformed

    private void menuRelatorioClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuRelatorioClienteActionPerformed
        // Gerando o relatório de clientes
        int confirma = JOptionPane.showConfirmDialog(null,"Confirma a impressão deste relatório?",
        "Atenção",JOptionPane.YES_NO_OPTION);
        
        if(confirma == JOptionPane.YES_OPTION){
            //imprimindo o relatório com o framework JasperReports
            try{
                //Usando a classe JasperPrint para preparar a impressão de um relatório
                JasperPrint print = JasperFillManager.fillReport("/home/lucas/reports/clientes.jasper", null, conexao);
                //A linha abaixo exibe o relatório através da classe JasperViewer
                JasperViewer.viewReport(print, false);
                
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }//GEN-LAST:event_menuRelatorioClienteActionPerformed

    private void menuRelatorioServicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuRelatorioServicoActionPerformed
        // Gerando relatório dos serviços
        int confirma = JOptionPane.showConfirmDialog(null,"Confirma a emissão deste relatório?","Atenção", JOptionPane.YES_NO_OPTION);
        
         if(confirma == JOptionPane.YES_OPTION){
             
             //Imprimindo o relatório com o framework JasperReports
            try{
                
                 //Usando a classe JasperPrint para preparar a impressão de um relatório
                 JasperPrint print = JasperFillManager.fillReport("/home/lucas/reports/servico.jasper", null, conexao);
                 //A linha abaixo exibe o relatório através da classe JasperViewer
                 JasperViewer.viewReport(print, false);

                
            }catch(Exception e){
                
                JOptionPane.showMessageDialog(null, e);
                
            }
        }
    }//GEN-LAST:event_menuRelatorioServicoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar Menu;
    private javax.swing.JDesktopPane desktop;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbl_Data;
    public static javax.swing.JLabel lbl_Usuario;
    private javax.swing.JMenuItem menuRelatorioCliente;
    private javax.swing.JMenuItem menuRelatorioServico;
    private javax.swing.JMenu menu_Ajuda;
    private javax.swing.JMenuItem menu_AjudaSobre;
    private javax.swing.JMenu menu_Cadastro;
    private javax.swing.JMenuItem menu_CadastroCliente;
    private javax.swing.JMenuItem menu_CadastroOS;
    public static javax.swing.JMenuItem menu_CadastroUsuario;
    private javax.swing.JMenu menu_Opcoes;
    private javax.swing.JMenuItem menu_OpcoesSair;
    public static javax.swing.JMenu menu_Relatorio;
    // End of variables declaration//GEN-END:variables
}
